title: 'Flutter Widget Livebook'
subtitle: 'An website built using Flutter for web to live preview widget samples online.'
description: ''
author: LiJianying <lijy91@foxmail.com>
language: en
supportedLanguages:
  en:
    key: 'en'
    name: 'English'
    flag: '/images/flags/us.svg'
    pathname: '/'
  fa_IR:
    key: 'fa_IR'
    dir: 'rtl'
    name: 'Persian'
    flag: '/images/flags/ir.svg'
    pathname: '/fa_IR'
  zh_CN:
    key: 'zh_CN'
    name: 'Chinese Simplified'
    flag: '/images/flags/cn.svg'
    pathname: '/zh_CN'
sidebar:
  '/':
    - key: 'basics'
      children:
        - '/basics/introduction'
        - '/basics/faq'
    - key: 'widgets'
      children:
        - '/widgets/AlertDialog'
        - '/widgets/Align'
        - '/widgets/AnimatedAlign'
        - '/widgets/AnimatedBuilder'
        - '/widgets/AnimatedContainer'
        - '/widgets/AnimatedCrossFade'
        - '/widgets/AnimatedDefaultTextStyle'
        - '/widgets/AnimatedList'
        - '/widgets/AnimatedOpacity'
        - '/widgets/AnimatedPadding'
        - '/widgets/AnimatedPhysicalModel'
        - '/widgets/AnimatedPositioned'
        - '/widgets/AnimatedSize'
        - '/widgets/AnimatedSwitcher'
        - '/widgets/AppBar'
        - '/widgets/AspectRatio'
        - '/widgets/BackdropFilter'
        - '/widgets/Banner'
        - '/widgets/Baseline'
        - '/widgets/BottomAppBar'
        - '/widgets/BottomNavigationBar'
        - '/widgets/BottomSheet'
        - '/widgets/ButtonBar'
        - '/widgets/Card'
        - '/widgets/Center'
        - '/widgets/Checkbox'
        - '/widgets/CheckboxListTile'
        - '/widgets/Chip'
        - '/widgets/CircleAvatar'
        - '/widgets/CircularProgressIndicator'
        - '/widgets/ClipOval'
        - '/widgets/ClipPath'
        - '/widgets/ClipRRect'
        - '/widgets/ClipRect'
        - '/widgets/Column'
        - '/widgets/ConstrainedBox'
        - '/widgets/Container'
        - '/widgets/CupertinoActionSheet'
        - '/widgets/CupertinoActivityIndicator'
        - '/widgets/CupertinoAlertDialog'
        - '/widgets/CupertinoButton'
        - '/widgets/CupertinoContextMenu'
        - '/widgets/CupertinoDatePicker'
        - '/widgets/CupertinoNavigationBar'
        - '/widgets/CupertinoPageScaffold'
        - '/widgets/CupertinoSlider'
        - '/widgets/CupertinoSwitch'
        - '/widgets/CupertinoTabBar'
        - '/widgets/CupertinoTimerPicker'
        - '/widgets/CustomPaint'
        - '/widgets/CustomScrollView'
        - '/widgets/DataTable'
        - '/widgets/DatePicker'
        - '/widgets/DecoratedBox'
        - '/widgets/DecoratedBoxTransition'
        - '/widgets/DefaultTextStyle'
        - '/widgets/Dismissible'
        - '/widgets/Divider'
        - '/widgets/Draggable'
        - '/widgets/Drawer'
        - '/widgets/DropdownButton'
        - '/widgets/Expanded'
        - '/widgets/ExpansionPanelList'
        - '/widgets/FlatButton'
        - '/widgets/Flexible'
        - '/widgets/FloatingActionButton'
        - '/widgets/Flow'
        - '/widgets/FlutterLogo'
        - '/widgets/Form'
        - '/widgets/GestureDetector'
        - '/widgets/GridView'
        - '/widgets/Icon'
        - '/widgets/IconButton'
        - '/widgets/Image'
        - '/widgets/IndexedStack'
        - '/widgets/InkWell'
        - '/widgets/LinearProgressIndicator'
        - '/widgets/ListTile'
        - '/widgets/ListView'
        - '/widgets/NestedScrollView'
        - '/widgets/Opacity'
        - '/widgets/OutlineButton'
        - '/widgets/OverflowBox'
        - '/widgets/Padding'
        - '/widgets/PageView'
        - '/widgets/PhysicalModel'
        - '/widgets/Placeholder'
        - '/widgets/PopupMenuButton'
        - '/widgets/Positioned'
        - '/widgets/PositionedTransition'
        - '/widgets/Radio'
        - '/widgets/RadioListTile'
        - '/widgets/RaisedButton'
        - '/widgets/RangeSlider'
        - '/widgets/RefreshIndicator'
        - '/widgets/RichText'
        - '/widgets/RotatedBox'
        - '/widgets/RotationTransition'
        - '/widgets/Row'
        - '/widgets/Scaffold'
        - '/widgets/Scrollbar'
        - '/widgets/SelectableText'
        - '/widgets/SimpleDialog'
        - '/widgets/SingleChildScrollView'
        - '/widgets/SizedBox'
        - '/widgets/SizedOverflowBox'
        - '/widgets/Slider'
        - '/widgets/SliverAppBar'
        - '/widgets/Stack'
        - '/widgets/Stepper'
        - '/widgets/Switch'
        - '/widgets/TabBar'
        - '/widgets/Table'
        - '/widgets/Text'
        - '/widgets/TextField'
        - '/widgets/TimePicker'
        - '/widgets/ToggleButtons'
        - '/widgets/Tooltip'
        - '/widgets/Transform'
        - '/widgets/VerticalDivider'
        - '/widgets/Wrap'
  '/blog':
    - key: 'all'
      children:
        - '/release-notes-1.12.13'
  '/flutter_flipperkit':
    - key: 'all'
      children:
        - '/'
